### ISSUE TITLE
How to config mclock_client queue in ceph mimic? How to distinguish different clients?

### ISSUE THREAD

**Issue by mosWendy** [ceph/dmclock#70]
I am now trying to run tests to see how mclock_client queue works on mimic. But when I tried to config tag (r,w,l) of each client, I found there are no options to distinguish different clients.
All I got are following options for mclock_opclass, which are used to distinguish different types of operations.

[root@ceph-node1 ~]# ceph daemon osd.0 config show | grep mclock
"osd_op_queue": "mclock_opclass",
 "osd_op_queue_mclock_client_op_lim": "100.000000",
    "osd_op_queue_mclock_client_op_res": "100.000000",
    "osd_op_queue_mclock_client_op_wgt": "500.000000",
    "osd_op_queue_mclock_osd_subop_lim": "0.000000",
    "osd_op_queue_mclock_osd_subop_res": "1000.000000",
    "osd_op_queue_mclock_osd_subop_wgt": "500.000000",
    "osd_op_queue_mclock_recov_lim": "0.001000",
    "osd_op_queue_mclock_recov_res": "0.000000",
    "osd_op_queue_mclock_recov_wgt": "1.000000",
    "osd_op_queue_mclock_scrub_lim": "100.000000",
    "osd_op_queue_mclock_scrub_res": "100.000000",
    "osd_op_queue_mclock_scrub_wgt": "500.000000",
    "osd_op_queue_mclock_snap_lim": "0.001000",
    "osd_op_queue_mclock_snap_res": "0.000000",
    "osd_op_queue_mclock_snap_wgt": "1.000000",

I am wondering if ceph mimic provide any configuration interfaces for mclock_client queue? Has anyone ever set up mclock_client queue successfully?

**Comment by ivancich** [comment]
I had started modifications to librados to support per-client configurations. But I was unable to complete that work before being moved to other projects. I believe @mkogan1 is working to complete that effort as he has time. 

There do appear to be ceph users using mclock (for example, see https://github.com/ceph/dmclock/pull/69), however I do not know if anyone is using mclock_client.

**Comment by qjpqzb** [comment]
@ivancich @mkogan1 
Hi, I have similar issues when I config "osd op queue" as "mclock_client" in ceph nautilus 14.2.9. I want to config (r, w, l) of each client to perform different QoS control for different clients.

I noticed that in "OSD CONFIG REFERENCE" section of CEPH documentation, it states that "the mClock based ClientQueue (mclock_client) also incorporates the client identifier in order to promote fairness between clients.", so I believe librados can support per-client configurations right now. but I found there are no options to set up "client identifier" to do so. All I got is the same options as Uanenang. 

I wonder how can I set up the CEPH configuration to config different (r, w, l) for different client? Thank you very much.

**Comment by ivancich** [comment]
@qjpqzb I've handed that project over to others on the ceph team and haven't worked on it in well over a year. I would post your question to the ceph-devel mailing list. Good luck!

**Comment by yongseokoh** [comment]
@ivancich Hi, nice to meet you (virtually). I am very interested in the client QoS feature. We plan to adopt or develop the client Qos feature in our large scale Ceph cluster due to the noisy neighbor problem.  Is the mclock_client scheduler working in Nautilus 14.2.11 version? I have tried to tune the r, w, and l values related to osd_op_queue_mclock_client_op_*, but it seems that the overall client performance isn't varied along with tunable values. (Lowered performance is expected as the limit value is configured.)

**Comment by zdover23** [comment]
I’m commenting here because this has documentation impact and I want to be
able to find this thread.

Zac Dover
Ceph Upstream Docs
